on: [push]

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run the action
        uses: potatoqualitee/mssqlsuite@v1
        with:
          install: sqlengine, sqlclient

      - name: Run sqlclient
        run: sqlcmd -S localhost -U sa -P dbatools.I0 -i /${GITHUB_WORKSPACE}/sql/test.sql
        # run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "SELECT @@version;"
